name: extroza
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  firebase_auth: ^5.6.0
  firebase_core: ^3.0.0 # Good practice to have this explicitly
  
  # --- FIX 1: ADD THE MISSING PACKAGE ---
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  package_info_plus: ^8.3.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.9
  intl: ^0.20.2
  flutter_contacts: ^1.1.8 
  flutter_webrtc: ^0.9.47
  permission_handler: ^12.0.0+1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- FIX 2: ENABLE THE ASSETS FOLDER ---
  # This section tells your app where to find images.
  assets:
    - assets/google.png
