name: extroza
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  firebase_auth: ^5.6.0
  firebase_core: ^3.0.0 
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  package_info_plus: ^8.3.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.9
  intl: ^0.20.2
  flutter_contacts: ^1.1.8 
  flutter_webrtc: ^0.14.2
  permission_handler: ^12.0.0+1


  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^19.3.0
  firebase_storage: ^12.1.1
  emoji_picker_flutter: ^4.3.0 
  cached_network_image: ^3.3.1
  uuid: ^4.4.0

# --- FIX: Overriding the 'web' dependency to resolve the conflict ---
dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
