// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      // --- THE FIX IS HERE ---
      // We are now returning the 'linux' options instead of throwing an error.
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- ADD THIS NEW SECTION ---
  // Fill these values from your Firebase Console
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'PASTE_YOUR_API_KEY_HERE',
    appId: 'PASTE_YOUR_APP_ID_HERE',
    messagingSenderId: 'PASTE_YOUR_MESSAGING_SENDER_ID_HERE',
    projectId: 'PASTE_YOUR_PROJECT_ID_HERE',
    storageBucket: 'extroza-app.appspot.com',
  );
  // --- END OF NEW SECTION ---

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0MnJA1EvyheFKWyOsUmJka40WMowCO_o',
    appId: '1:925103203417:web:592fade228724e60ecbd48',
    messagingSenderId: '925103203417',
    projectId: 'extroza-app',
    authDomain: 'extroza-app.firebaseapp.com',
    storageBucket: 'extroza-app.firebasestorage.app',
    measurementId: 'G-FK4YC4NZPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSjDNOIisJYKZDwK81gdF18RQXG_XNbzk',
    appId: '1:925103203417:android:5a63b27fe16e222becbd48',
    messagingSenderId: '925103203417',
    projectId: 'extroza-app',
    storageBucket: 'extroza-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY_XyeSRQVYRsv-duMIcoDoGjRjuVv-AI',
    appId: '1:925103203417:ios:95719c580bceab56ecbd48',
    messagingSenderId: '925103203417',
    projectId: 'extroza-app',
    storageBucket: 'extroza-app.firebasestorage.app',
    iosBundleId: 'com.example.extroza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY_XyeSRQVYRsv-duMIcoDoGjRjuVv-AI',
    appId: '1:925103203417:ios:95719c580bceab56ecbd48',
    messagingSenderId: '925103203417',
    projectId: 'extroza-app',
    storageBucket: 'extroza-app.firebasestorage.app',
    iosBundleId: 'com.example.extroza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0MnJA1EvyheFKWyOsUmJka40WMowCO_o',
    appId: '1:925103203417:web:6d78d83ece9e0c48ecbd48',
    messagingSenderId: '925103203417',
    projectId: 'extroza-app',
    authDomain: 'extroza-app.firebaseapp.com',
    storageBucket: 'extroza-app.firebasestorage.app',
    measurementId: 'G-53DCSYK83E',
  );

}